[package]
name = "vmath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.18"
bstream = { path = "../bstream" }
bstream-macro = { path = "../bstream-macro" }
byteorder = "1.5.0"
