[package]
name = "physics-discrete"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vmath = { path = "../vmath" }
num-traits = "0.2.18"
