[package]
name = "bstream-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
bstream = { path = "../bstream" }
syn = "2.0.60"
proc-macro2 = "1.0.81"